### ISSUE TITLE
There are types at dist/index.d.ts but this result could not be resolved when respecting package.json "exports"

### ISSUE THREAD

**Issue by lucamartinelli-gl** [wattanx/vue-color-picker#7]
On Nuxt3, Node 20.5.0

I receive this error when importing the library:

There are types at './node_modules/@wattanx/vue-color-picker/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@wattanx/vue-color-picker' library may need to update its package.json or typings.

I noticed that is sufficient change package.json as below

```
...
 "exports": {
    ".": {
      "require": "./dist/index.js",
      "default": "./dist/index.mjs",
      "types": "./dist/index.d.ts" <- add this line
    }
  },
...
```

**Comment by wattanx** [comment]
We plan to fix this soon, but here is a workaround

```ts
export default defineNuxtConfig({
  typescript: {
    tsConfig: {
      compilerOptions: {
        resolvePackageJsonExports: false,
      },
    },
  },
})
```

**Comment by lucamartinelli-gl** [comment]
It worked, thakn you!
